{{/*
Environment Variables for Rasa Containers
*/}}
{{- define "rasa.containers.env" -}}
{{- with .Values.rasa.settings }}
{{- if and .endpoints.models.enabled .endpoints.models.token.enabled -}}
- name: MODEL_SERVER_TOKEN
  valueFrom:
    secretKeyRef:
      name: {{ .endpoints.models.token.secretName }}
      key: {{ .endpoints.models.token.secretKey }}
{{- end }}
{{- if and $.Values.rasa.enabled (not $.Values.rasa.plus.enabled) (not $.Values.rasaProServices.enabled) }}
- name: "RASA_TELEMETRY_ENABLED"
  value: {{ .telemetry.enabled | quote }}
- name: "RASA_TELEMETRY_DEBUG"
  value: {{ .telemetry.debug | quote }}
{{- end }}
- name: "MPLCONFIGDIR"
  value: "/tmp/.matplotlib"
- name: "TF_CPP_MIN_LOG_LEVEL"
  value: "2"
- name: "RASA_TOKEN"
  valueFrom:
    secretKeyRef:
      name: {{ .token.secretName }}
      key: {{ .token.secretKey }}
- name: "JWT_SECRET"
  valueFrom:
    secretKeyRef:
      name: {{ .jwtSecret.secretName }}
      key: {{ .jwtSecret.secretKey }}
{{- end }}
{{- with .Values.rasa.plus.settings }}
{{- if or $.Values.rasaProServices.enabled $.Values.rasa.plus.enabled }}
- name: "RASA_PRO_LICENSE" 
  valueFrom:
    secretKeyRef:
      name: {{ .rasaProLicence.secretName }}
      key: {{ .rasaProLicence.secretKey }}
# Telemetry
- name: "RASA_PRO_TELEMETRY_ENABLED"
  value: {{ .telemetry.enabled | quote }}
- name: "RASA_PRO_TELEMETRY_DEBUG"
  value: {{ .telemetry.debug | quote }}
# Hashicorp Secret Manager
{{- if .secretsManager.enabled }}
- name: "SECRET_MANAGER"
  value: {{ .secretsManager.secretManager | quote }}
- name: "VAULT_HOST"
  value: {{ .secretsManager.vaultHost | quote }}
- name: "VAULT_TOKEN"
  valueFrom:
    secretKeyRef:
      name: {{ .secretsManager.vaultToken.secretName }}
      key: {{ .secretsManager.vaultToken.secretKey }}
- name: "VAULT_RASA_SECRETS_PATH"
  value: {{ .secretsManager.vaultRasaSecretsPath | quote }}
- name: "VAULT_TRANSIT_MOUNT_POINT"
  value: {{ .secretsManager.vaultTransitMountPoint | quote }}
{{- end }}
{{- end }}
{{- if or $.Values.rasa.enabled $.Values.rasa.plus.enabled }}
- name: "RASA_ENVIRONMENT"
  value: {{ .rasaEnvironment | quote }}
# Lock Store
- name: "TICKET_LOCK_LIFETIME"
  value: {{ .lockStore.ticketLockLifetime }}
# Tracing
- name: "TRACING_SERVICE_NAME"
  value: {{ .tracing.serviceName | quote }}
# Sanic Server
- name: "SANIC_BACKLOG"
  value: {{ .tracing.backlog | quote }}
- name: "SANIC_WORKERS"
  value: {{ .tracing.workers }}
# Postgres Tracker Store
- name: "POSTGRESQL_SCHEMA"
  value: {{ .postgresTrackerStore.schema | quote }}
- name: "POSTGRESQL_POOL_SIZE"
  value: {{ .postgresTrackerStore.poolSize }}
- name: "POSTGRESQL_MAX_OVERFLOW"
  value: {{ .postgresTrackerStore.maxOverflow }}
# RabbitMQ
- name: "RABBITMQ_SSL_CLIENT_CERTIFICATE"
  valueFrom:
    secretKeyRef:
      name: {{ .rabbitmq.sslClientCertificate.secretName }}
      key: {{ .rabbitmq.sslClientCertificate.secretKey }}
- name: "RABBITMQ_SSL_CLIENT_KEY"
  valueFrom:
    secretKeyRef:
      name: {{ .rabbitmq.sslClientKey.secretName }}
      key: {{ .rabbitmq.sslClientKey.secretKey }}
# Logging
- name: "LOG_LEVEL"
  value: {{ .logging.logLevel | quote | upper }}
- name: "LOG_LEVEL_LIBRARIES"
  value: {{ .logging.logLevelLibraries | quote | upper }}
- name: "LOG_LEVEL_MATPLOTLIB"
  value: {{ .logging.logLevelMatplotlib | quote | upper }}
- name: "LOG_LEVEL_KAFKA"
  value: {{ .logging.logLevelKafka | quote | upper }}
- name: "LOG_LEVEL_RABBITMQ"
  value: {{ .logging.logLevelRabbitMq | quote | upper }}
- name: "LOG_LEVEL_PRESIDIO"
  value: {{ .logging.logLevelPresidio | quote | upper }}
- name: "LOG_LEVEL_FAKER"
  value: {{ .logging.logLevelFaker | quote | upper }}
- name: "FORCE_JSON_LOGGING"
  value: {{ .logging.forceJsonLogging | quote | upper }}
# Cache
- name: "RASA_MAX_CACHE_SIZE"
  value: {{ .cache.maxSize | quote }}
- name: "RASA_CACHE_NAME"
  value: {{ .cache.name | quote }}
- name: "RASA_CACHE_DIRECTORY"
  value: {{ .cache.directory | quote }}
# Duckling
- name: "RASA_DUCKLING_HTTP_URL"
  value: {{ .ducklingHttpUrl | quote }}
# Tensorflow
- name: "TF_GPU_MEMORY_ALLOC"
  value: {{ .tensorflow.gpuMemoryAlloc | quote }}
- name: "TF_INTER_OP_PARALLELISM_THREADS"
  value: {{ .tensorflow.interOpParallelismThreads | quote }}
- name: "TF_INTRA_OP_PARALLELISM_THREADS"
  value: {{ .tensorflow.intraOpParallelismThreads | quote }}
- name: "TF_DETERMINISTIC_OPS"
  value: {{ .tensorflow.deterministicOps | quote }}
- name: "RASA_SHELL_STREAM_READING_TIMEOUT_IN_SECONDS"
  value: {{ .shellStreamReadingTimeoutInSeconds | quote }}
- name: "MAX_NUMBER_OF_PREDICTIONS"
  value: {{.maxNumberOfPreditions | quote }}
{{- end }}
{{- end }}
{{- if .Values.rasa.extraEnv }}
{{ toYaml .Values.rasa.extraEnv }}
{{- end }}
{{- end -}}
