{{/*
Environment Variables for Rasa Containers
*/}}
{{- define "rasa.containers.env" -}}
{{- if and .Values.rasa.settings.endpoints.models.enabled .Values.rasa.settings.endpoints.models.token.enabled -}}
- name: MODEL_SERVER_TOKEN
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.settings.endpoints.models.token.secretName }}
      key: {{ .Values.rasa.settings.endpoints.models.token.secretKey }}
{{- end }}
{{- if and (not .Values.rasa.plus.enabled) (not .Values.rasaProServices.enabled) }}
- name: "RASA_TELEMETRY_ENABLED"
  value: {{ .Values.rasa.settings.telemetry.enabled | quote }}
- name: "RASA_TELEMETRY_DEBUG"
  value: {{ .Values.rasa.settings.telemetry.debug | quote }}
{{- end }}
- name: "MPLCONFIGDIR"
  value: "/tmp/.matplotlib"
- name: "TF_CPP_MIN_LOG_LEVEL"
  value: "2"
- name: "RASA_TOKEN"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.settings.token.secretName }}
      key: {{ .Values.rasa.settings.token.secretKey }}
- name: "JWT_SECRET"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.settings.jwtSecret.secretName }}
      key: {{ .Values.rasa.settings.jwtSecret.secretKey }}
{{- if and (not .Values.rasa.plus.enabled) .Values.rasa.extraEnv }} # not used in rasa plus
{{ toYaml .Values.rasa.extraEnv }}
{{- end }}
{{- if .Values.rasaProServices.enabled }}
- name: "RASA_PRO_LICENSE" 
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.rasaProLicence.secretName }}
      key: {{ .Values.rasa.plus.settings.rasaProLicence.secretKey }}
# Telemetry
- name: "RASA_PRO_TELEMETRY_ENABLED"
  value: {{ .Values.rasa.plus.settings.telemetry.enabled | quote }}
- name: "RASA_PRO_TELEMETRY_DEBUG"
  value: {{ .Values.rasa.plus.settings.telemetry.debug | quote }}
# Hashicorp Secret Manager
- name: "SECRET_MANAGER"
  value: {{ .Values.rasa.plus.settings.hashicorpSecretManager.secretManager | quote }}
- name: "VAULT_HOST"
  value: {{ .Values.rasa.plus.settings.hashicorpSecretManager.vaultHost | quote }}
- name: "VAULT_TOKEN"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.hashicorpSecretManager.vaultToken.secretName }}
      key: {{ .Values.rasa.plus.settings.hashicorpSecretManager.vaultToken.secretKey }}
- name: "VAULT_RASA_SECRETS_PATH"
  value: {{ .Values.rasa.plus.settings.hashicorpSecretManager.vaultRasaSecretsPath | quote }}
- name: "VAULT_TRANSIT_MOUNT_POINT"
  value: {{ .Values.rasa.plus.settings.hashicorpSecretManager.vaultTransitMountPoint | quote }}
{{- end }}
{{- if or .Values.rasa.enabled .Values.rasa.plus.enabled }}
- name: "RASA_ENVIRONMENT"
  value: {{ .Values.rasa.plus.settings.rasaEnvironment | quote }}
# Lock Store
- name: "TICKET_LOCK_LIFETIME"
  value: {{ .Values.rasa.plus.settings.lockStore.ticketLockLifetime }}
# Tracing
- name: "TRACING_SERVICE_NAME"
  value: {{ .Values.rasa.plus.settings.tracing.serviceName | quote }}
# Sanic Server
- name: "SANIC_BACKLOG"
  value: {{ .Values.rasa.plus.settings.tracing.backlog | quote }}
- name: "SANIC_WORKERS"
  value: {{ .Values.rasa.plus.settings.tracing.workers }}
# Postgres Tracker Store
- name: "POSTGRESQL_SCHEMA"
  value: {{ .Values.rasa.plus.settings.postgresTrackerStore.schema | quote }}
- name: "POSTGRESQL_POOL_SIZE"
  value: {{ .Values.rasa.plus.settings.postgresTrackerStore.poolSize }}
- name: "POSTGRESQL_MAX_OVERFLOW"
  value: {{ .Values.rasa.plus.settings.postgresTrackerStore.maxOverflow }}
# RabbitMQ
- name: "RABBITMQ_SSL_CLIENT_CERTIFICATE"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.rabbitmq.sslClientCertificate.secretName }}
      key: {{ .Values.rasa.plus.settings.rabbitmq.sslClientCertificate.secretKey }}
- name: "RABBITMQ_SSL_CLIENT_KEY"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.rabbitmq.sslClientKey.secretName }}
      key: {{ .Values.rasa.plus.settings.rabbitmq.sslClientKey.secretKey }}
- name: "RABBITMQ_SSL_CA_FILE"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.rabbitmq.sslCAFile.secretName }}
      key: {{ .Values.rasa.plus.settings.rabbitmq.sslCAFile.secretKey }}
- name: "RABBITMQ_SSL_KEY_PASSWORD"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.rabbitmq.sslKeyPassword.secretName }}
      key: {{ .Values.rasa.plus.settings.rabbitmq.sslKeyPassword.secretKey }}
# Logging
- name: "LOG_LEVEL"
  value: {{ .Values.rasa.plus.settings.logging.logLevel | quote | upper }}
- name: "LOG_LEVEL_LIBRARIES"
  value: {{ .Values.rasa.plus.settings.logging.logLevelLibraries | quote | upper }}
- name: "LOG_LEVEL_KAFKA"
  value: {{ .Values.rasa.plus.settings.logging.logLevelKafka | quote | upper }}
- name: "LOG_LEVEL_RABBITMQ"
  value: {{ .Values.rasa.plus.settings.logging.logLevelRabbitMq | quote | upper }}
- name: "LOG_LEVEL_PRESIDIO"
  value: {{ .Values.rasa.plus.settings.logging.logLevelPresidio | quote | upper }}
- name: "LOG_LEVEL_FAKER"
  value: {{ .Values.rasa.plus.settings.logging.logLevelFaker | quote | upper }}
- name: "FORCE_JSON_LOGGING"
  value: {{ .Values.rasa.plus.settings.logging.forceJsonLogging | quote | upper }}
# AWS Model Storage
- name: "AWS_SECRET_ACCESS_KEY"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.modelStorage.aws.secretAccessKey.secretName }}
      key: {{ .Values.rasa.plus.settings.modelStorage.aws.secretAccessKey.secretKey }}
- name: "AWS_ACCESS_KEY_ID"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.modelStorage.aws.accessKeyId.secretName }}
      key: {{ .Values.rasa.plus.settings.modelStorage.aws.accessKeyId.secretKey }}
- name: "AWS_DEFAULT_REGION"
  value: {{ .Values.rasa.plus.settings.modelStorage.aws.defaultRegion | quote }}
- name: "BUCKET_NAME"
  value: {{ .Values.rasa.plus.settings.modelStorage.aws.bucketName | quote }}
- name: "AWS_ENDPOINT_URL"
  value: {{ .Values.rasa.plus.settings.modelStorage.aws.endpointUrl | quote }}
# Azure Model Storage
- name: "AZURE_ACCOUNT_KEY"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.modelStorage.azure.accountKey.secretName }}
      key: {{ .Values.rasa.plus.settings.modelStorage.azure.accountKey.secretKey }}
- name: "AZURE_CONTAINER"
  value: {{ .Values.rasa.plus.settings.modelStorage.azure.container | quote }}
- name: "AZURE_ACCOUNT_NAME"
  value: {{ .Values.rasa.plus.settings.modelStorage.azure.accountName | quote }}
# GCP Model Storage
- name: "GOOGLE_APPLICATION_CREDENTIALS"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.rasa.plus.settings.modelStorage.gcp.applicationCredentials.secretName }}
      key: {{ .Values.rasa.plus.settings.modelStorage.gcp.applicationCredentials.secretKey }}
# Cache
- name: "RASA_MAX_CACHE_SIZE"
  value: {{ .Values.rasa.plus.settings.cache.maxSize | quote }}
- name: "RASA_CACHE_NAME"
  value: {{ .Values.rasa.plus.settings.cache.name | quote }}
- name: "RASA_CACHE_DIRECTORY"
  value: {{ .Values.rasa.plus.settings.cache.directory | quote }}
# Duckling
- name: "RASA_DUCKLING_HTTP_URL"
  value: {{ .Values.rasa.plus.settings.ducklingHttpUrl | quote }}
# Tensorflow
- name: "TF_GPU_MEMORY_ALLOC"
  value: {{ .Values.rasa.plus.settings.tensorflow.gpuMemoryAlloc | quote }}
- name: "TF_INTER_OP_PARALLELISM_THREADS"
  value: {{ .Values.rasa.plus.settings.tensorflow.interOpParallelismThreads | quote }}
- name: "TF_INTRA_OP_PARALLELISM_THREADS"
  value: {{ .Values.rasa.plus.settings.tensorflow.intraOpParallelismThreads | quote }}
- name: "TF_DETERMINISTIC_OPS"
  value: {{ .Values.rasa.plus.settings.tensorflow.deterministicOps | quote }}
- name: "RASA_SHELL_STREAM_READING_TIMEOUT_IN_SECONDS"
  value: {{ .Values.rasa.plus.settings.shellStreamReadingTimeoutInSeconds | quote }}
- name: "MAX_NUMBER_OF_PREDICTIONS"
  value: {{ .Values.rasa.plus.settings.maxNumberOfPreditions | quote }}
{{- if .Values.internal }}
# Internal usage only
- name: "RASA_TELEMETRY_WRITE_KEY"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.internal.secretName }}
      key: {{ .Values.internal.secretKey }}
- name: "RASA_EXCEPTION_WRITE_KEY"
  valueFrom:
    secretKeyRef:
      name: {{ .Values.internal.secretName }}
      key: {{ .Values.internal.secretKey }}
{{- end }}
{{- if .Values.rasa.plus.settings.additionalSettings }} # not used in rasa plus
{{ toYaml .Values.rasa.plus.settings.additionalSettings }}
{{- end }}
{{- end }}
{{- end -}}
