{{/*
Environment Variables for Rasa Containers
*/}}
{{- define "rasa.containers.env" -}}
{{- with .Values.rasa.settings }}
{{- if and $.Values.rasa.enabled (not $.Values.rasa.plus.enabled) (not $.Values.rasaProServices.enabled) }}
- name: "RASA_TELEMETRY_ENABLED"
  value: {{ .telemetry.enabled | quote }}
- name: "RASA_TELEMETRY_DEBUG"
  value: {{ .telemetry.debug | quote }}
{{- end -}}
{{- if or $.Values.duckling.enabled (not (empty $.Values.rasa.settings.ducklingHttpUrl)) -}}
- name: "RASA_DUCKLING_HTTP_URL"
  value: "{{ include "rasa.ducklingUrl" $ }}"
{{- end }}
- name: "RASA_TOKEN"
  valueFrom:
    secretKeyRef:
      name: {{ .authToken.secretName }}
      key: {{ .authToken.secretKey }}
- name: "JWT_SECRET"
  valueFrom:
    secretKeyRef:
      name: {{ .jwtSecret.secretName }}
      key: {{ .jwtSecret.secretKey }}
{{- if or $.Values.rasaProServices.enabled $.Values.rasa.plus.enabled }}
- name: "RASA_PRO_LICENSE" 
  valueFrom:
    secretKeyRef:
      name: {{ $.Values.rasaProLicence.secretName }}
      key: {{ $.Values.rasaProLicence.secretKey }}
# Telemetry
- name: "RASA_PRO_TELEMETRY_ENABLED"
  value: {{ .telemetry.enabled | quote }}
- name: "RASA_PRO_TELEMETRY_DEBUG"
  value: {{ .telemetry.debug | quote }}
{{- end }}
{{- if or $.Values.rasa.enabled $.Values.rasa.plus.enabled }}
- name: "RASA_ENVIRONMENT"
  value: {{ .environment | quote }}
# Logging
- name: "LOG_LEVEL"
  value: {{ .logging.logLevel | quote | upper }}
{{- end }}
{{- end }}
{{- if .Values.rasa.additionalEnv }}
{{ toYaml .Values.rasa.additionalEnv }}
{{- end }}
{{- end -}}
