{{- define "rasa.containers.volumes" -}}
- name: config-dir
  emptyDir: {}
- name: "rasa-configuration"
  configMap:
    name: rasa-configmap
    items:
      - key: "endpoints"
        path: "endpoints.yml"
      - key: "credentials"
        path: "credentials.yml"
- name: models
  emptyDir: {}
- name: app-dir
  emptyDir: {}
- name: jwt-secret
  secret:
    secretName: {{ .Values.rasa.settings.jwtSecret.secretName }}
- name: rasa-token
  secret:
    secretName: {{ .Values.rasa.settings.authToken.secretName }}
{{- end -}}

{{- define "rasa.containers.volumeMounts" -}}
# Mount the temporary directory for the Rasa global configuration
- name: "config-dir"
  mountPath: "/.config"
- mountPath: "/app/endpoints.yml"
  subPath: "endpoints.yml"
  name: "rasa-configuration"
  readOnly: true
- mountPath: "/app/credentials.yml"
  subPath: "credentials.yml"
  name: "rasa-configuration"
  readOnly: true
- mountPath: "/app/secret/jwt-secret"
  name: jwt-secret
- mountPath: "/app/secret/rasa-token"
  name: rasa-token
{{- end -}}
