{{- define "rasa.containers.env" -}}
{{- if and (eq (include "rasa.endpoints.models.enabled" .) "true") .Values.rasa.settings.endpoints.models.token }}
- name: MODEL_SERVER_TOKEN
  valueFrom:
    secretKeyRef:
      name: {{ include "rasa.fullname" . }}-secrets
      key: model-server-token
{{- end }}
- name: "RASA_TELEMETRY_ENABLED"
  value: {{ .Values.rasa.settings.telemetry.enabled | quote }}
- name: "MPLCONFIGDIR"
  value: "/tmp/.matplotlib"
- name: "TF_CPP_MIN_LOG_LEVEL"
  value: "2"
{{- if .Values.rasa.settings.rasaX.enabled }}
- name: "RASA_X_TOKEN"
  valueFrom:
    secretKeyRef:
      name: {{ include "rasa.fullname" . }}-secrets
      key: "rasa-x-token"
{{- end }}
- name: "RASA_TOKEN"
  valueFrom:
    secretKeyRef:
      name: {{ include "rasa.fullname" . }}-secrets
      key: "rasa-token"
- name: "JWT_SECRET"
  valueFrom:
    secretKeyRef:
      name: {{ include "rasa.fullname" . }}-secrets
      key: "jwt-secret"
{{- if .Values.rasa.extraEnv }}
{{ toYaml .Values.rasa.extraEnv }}
{{- end }}
{{- end -}}
