# Test values for Studio chart
# This file contains minimal configuration for testing the chart

# Disable external dependencies for testing
replicated:
  enabled: false

rasa:
  enabled: false

# Minimal backend configuration
backend:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Minimal web client configuration
webClient:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Disable ingress for testing
ingress:
  enabled: false

# Database configuration for testing
# Using default PostgreSQL configuration with minimal settings
database:
  host: "localhost"
  port: "5432"
  username: "test"
  preferSSL: "false"

# Disable Keycloak for testing
keycloak:
  enabled: false

# Minimal event ingestion
eventIngestion:
  enabled: true
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
