# Test values for Studio chart
# This file contains minimal configuration for testing the chart

# Disable external dependencies for testing
replicated:
  enabled: false

rasa:
  enabled: false

# Minimal backend configuration
backend:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  # Add readiness probe for backend health checks
  readinessProbe:
    enabled: true
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Minimal web client configuration
webClient:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Database configuration for testing
# Minimal config for pg_isready and SSL settings
config:
  database:
    host: "postgres-test"
    port: "5432"
    username: "test"
    preferSSL: "false"
    rejectUnauthorized: ""
    keycloakDatabaseName: "keycloak"

# Disable Keycloak for testing
keycloak:
  enabled: true
  ingress:
    enabled: false

# Minimal event ingestion
eventIngestion:
  enabled: false
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
