# Test values for Studio chart
# This file contains minimal configuration for testing the chart

# Disable external dependencies for testing
replicated:
  enabled: false

rasa:
  enabled: false

# Minimal backend configuration
backend:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  # Add readiness probe for backend health checks
  readinessProbe:
    enabled: true
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  # Add init containers for testing
  initContainers:
    - name: wait-for-keycloak
      image: curlimages/curl:8.4.0
      command: ['sh', '-c']
      args:
        - |
          echo "Waiting for Keycloak to be ready..."
          until curl -f --connect-timeout 5 --max-time 10 \
            http://{{ include "studio.fullname" . }}-keycloak:{{ .Values.keycloak.service.port }}/auth || exit 1; do
            echo "Keycloak is not ready yet, waiting..."
            sleep 5
          done
          echo "Keycloak is ready!"
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 25m
          memory: 32Mi

# Minimal web client configuration
webClient:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Database configuration for testing
# Minimal config for pg_isready and SSL settings
config:
  database:
    host: "postgres-test"
    port: "5432"
    username: "test"
    preferSSL: "false"
    rejectUnauthorized: ""
    keycloakDatabaseName: "keycloak"

# Disable Keycloak for testing
keycloak:
  enabled: true
  ingress:
    enabled: false

# Minimal event ingestion
eventIngestion:
  enabled: false
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
