# Test values for Studio chart
# This file contains minimal configuration for testing the chart

# Disable external dependencies for testing
replicated:
  enabled: false

rasa:
  enabled: false

# Minimal backend configuration
backend:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  # Add readiness probe for backend health checks
  readinessProbe:
    enabled: true
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  # Add init containers for testing
  initContainers:
    - name: wait-for-keycloak
      image: alpine:3.18
      command: ['sh', '-c']
      args:
        - |
          echo "Installing kubectl and curl..."
          apk add --no-cache curl
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl /usr/local/bin/
          
          echo "Waiting for Keycloak to be ready..."
          # Find the Keycloak service and wait for it to be ready
          while true; do
            KEYCLOAK_SERVICE=$(kubectl get svc -n test-namespace | grep -E ".*-keycloak$" | awk '{print $1}' | head -1)
            if [ -n "$KEYCLOAK_SERVICE" ]; then
              echo "Found Keycloak service: $KEYCLOAK_SERVICE"
              if curl -f --connect-timeout 5 --max-time 10 http://$KEYCLOAK_SERVICE:80/auth; then
                echo "Keycloak is ready!"
                break
              fi
            fi
            echo "Keycloak is not ready yet, waiting..."
            sleep 5
          done
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 25m
          memory: 32Mi

# Minimal web client configuration
webClient:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Database configuration for testing
# Minimal config for pg_isready and SSL settings
config:
  database:
    host: "postgres-test"
    port: "5432"
    username: "test"
    preferSSL: "false"
    rejectUnauthorized: ""
    keycloakDatabaseName: "keycloak"

# Disable Keycloak for testing
keycloak:
  enabled: true
  ingress:
    enabled: false


# Minimal event ingestion
eventIngestion:
  enabled: false
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
