# Test values for Studio chart
# This file contains minimal configuration for testing the chart
#
# Timeout Strategy:
# - Chart-testing timeout: 20m (set in ct.yaml)
# - Backend liveness probe: 180s initial delay + 8 failures × 20s = 340s total (5.7 minutes)
# - Backend readiness probe: 180s initial delay + 10 failures × 20s = 380s total (6.3 minutes)
# - Total probe time: ~12 minutes - well within the 20m chart-testing timeout

# Disable external dependencies for testing
replicated:
  enabled: false

rasa:
  enabled: false

# Minimal backend configuration
backend:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  # Add liveness probe for backend health checks
  livenessProbe:
    enabled: true
    httpGet:
      path: /api/health
      port: 4000
    initialDelaySeconds: 180
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 8
  # Add readiness probe for backend health checks
  readinessProbe:
    enabled: true
    httpGet:
      path: /api/health
      port: 4000
    initialDelaySeconds: 180
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 10
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  # No init containers - let backend handle Keycloak connection
  initContainers: []

# Minimal web client configuration
webClient:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Database configuration for testing
# Minimal config for pg_isready and SSL settings
config:
  database:
    host: "postgres-test"
    port: "5432"
    username: "test"
    preferSSL: "false"
    rejectUnauthorized: ""
    keycloakDatabaseName: "keycloak"

# Enable Keycloak for testing
keycloak:
  enabled: true
  ingress:
    enabled: false


# Minimal event ingestion
eventIngestion:
  enabled: false
