# Test values for Studio chart
# This file contains minimal configuration for testing the chart
#
# Timeout Strategy:
# - Chart-testing timeout: 45m (set in ct.yaml)
# - Backend liveness probe: 300s initial delay + 12 failures × 30s = 660s total (11 minutes)
# - Backend readiness probe: 300s initial delay + 15 failures × 30s = 750s total (12.5 minutes)
# - Keycloak liveness probe: 120s initial delay + 8 failures × 15s = 240s total (4 minutes)
# - Keycloak readiness probe: 120s initial delay + 10 failures × 10s = 220s total (3.7 minutes)
# - Total probe time: ~31 minutes - well within the 45m chart-testing timeout

# Disable external dependencies for testing
replicated:
  enabled: false

rasa:
  enabled: false

# Minimal backend configuration
backend:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  # Add liveness probe for backend health checks
  livenessProbe:
    enabled: true
    httpGet:
      path: /api/health
      port: 4000
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 12
  # Add readiness probe for backend health checks
  readinessProbe:
    enabled: true
    httpGet:
      path: /api/health
      port: 4000
    initialDelaySeconds: 300
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 15
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  # No init containers - let backend handle Keycloak connection
  initContainers: []

# Minimal web client configuration
webClient:
  enabled: true
  replicaCount: 1
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Database configuration for testing
# Minimal config for pg_isready and SSL settings
config:
  database:
    host: "postgres-test"
    port: "5432"
    username: "test"
    preferSSL: "false"
    rejectUnauthorized: ""
    keycloakDatabaseName: "keycloak"

# Enable Keycloak for testing
keycloak:
  enabled: true
  ingress:
    enabled: false
  # Add liveness probe for Keycloak health checks
  livenessProbe:
    enabled: true
    httpGet:
      path: /auth
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 8
  # Add readiness probe for Keycloak health checks
  readinessProbe:
    enabled: true
    httpGet:
      path: /auth
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10


# Minimal event ingestion
eventIngestion:
  enabled: false
