rasa:
  - changed-files:
      - any-glob-to-any-file: charts/rasa/**
studio:
  - changed-files:
      - any-glob-to-any-file: charts/studio/**
op-kits:
  - changed-files:
      - any-glob-to-any-file: charts/op-kits/**
# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'
