{{- define "troubleshoot.collectors.shared" -}}
- clusterInfo: {}
- clusterResources: {}
- registryImages:
    images:
      - europe-west3-docker.pkg.dev/rasa-releases/studio/studio-backend:{{ .Values.tag }}
      - europe-west3-docker.pkg.dev/rasa-releases/studio/studio-web-client:{{ .Values.tag }}
      - europe-west3-docker.pkg.dev/rasa-releases/studio/studio-keycloak:{{ .Values.tag }}
      - europe-west3-docker.pkg.dev/rasa-releases/studio/studio-event-ingestion:{{ .Values.tag }}
      - europe-west3-docker.pkg.dev/rasa-releases/dependencies/replicated-sdk:v1.0.0-beta.27
{{- end -}}

{{- define "troubleshoot.analyzers.shared" -}}
- clusterVersion:
    checkName: Is this cluster running a supported Kubernetes verison
    outcomes:
      - fail:
          when: "< 1.24.0"
          message: This Rasa Studio Helm chart is only supported on Kubernetes 1.24 or later
          uri: https://www.kubernetes.io
      - warn:
          when: "< 1.26.0"
          message: |
            You can run Rasa Studio Helm on your current cluster version, but your cluster is no longer supported
            by the Kubernetes community. If you have extended support available from your Kubernetes
            vendor you can ignore this warning.
          uri: https://kubernetes.io
      - pass:
          message: |
            Your current Kubernetes version is able to run Rasa Studio Helm using this Helm chart and is a
            version currently supported by the Kubernets community.
- containerRuntime:
    checkName: Does this Kubernetes cluster use a supported container runtime
    outcomes:
      - pass:
          when: "== containerd"
          message: You are running the ContainerD runtime that is supported by this chart.
      - fail:
          message: |
            The Helm chart requires the ContainerD container runtime, which is not the runtime
            configured in your clusster.
- distribution:
    checkName: Are we installing into a supported Kubernetes distribution
    outcomes:
      - warn:
          when: "== docker-desktop"
          message: |
            You are able to run Rasa Studio Helm in Docker Desktop, but we recommend using a different
            Kubernetes distribution for your production installation.
      - warn:
          when: "== microk8s"
          message: |
            You are able to run Rasa Studio in MicroK8s, but we recommend using a different
            Kubernetes distribution for your production installation.
      - warn:
          when: "== minikube"
          message: |
            You are able to run Rasa Studio in Minikube, but we recommend using a different
            Kubernetes distribution for your production installation.
      - pass:
          when: "== eks"
          message: Amazon EKS is a suppored Kubernetes distribution to run Rasa Studio in production
      - pass:
          when: "== gke"
          message: Google Kubernetes Engine is a suppored Kubernetes distribution to run Rasa Studio in production
      - pass:
          when: "== aks"
          message: Azure Kubernetes Services is a supported Kubernetes distributiion to run Rasa Studio in production
      - pass:
          message: We are unable to detect the Kubernetes distribution you are running but you should give it a try
- nodeResources:
    checkName: Are sufficient CPU resources available in the cluster
    outcomes:
      - fail:
          when: "sum(cpuAllocatable) < 4000m"
          message: Your cluster currently has too few CPU resources available to install Rasa Studio
      - pass:
          message: Your cluster has sufficient CPU resources available to install Rasa Studio
- nodeResources:
    checkName: Is sufficient memory available in the cluster
    outcomes:
      - fail:
          when: "min(memoryAllocatable) < 8Gi"
          message: Your cluster currently has too little memory available to install Rasa Studio
      - pass:
          message: Your cluster has sufficient memory available to install Rasa Studio
- registryImages:
    name: Registry Images
    checkName: Registry Images
    outcomes:
      - fail:
        when: "missing > 0"
        message: Images are missing from registry
      - warn:
          when: "errors > 0"
          message: Failed to check if images are present in registry. This is expected if you are running in the AirGap mode.
      - pass:
          message: All images are present in registry
{{- end -}}
