{{- if .Values.backend.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "studio.fullname" . }}-database-migration
  labels:
    {{- include "studio.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- if .Values.backend.migration.waitForIt }}
      initContainers:
        - name: wait-for-postgresql
          image: {{ .Values.backend.migration.waitFotItContainer.image }}
          command: ['sh', '-c', 'until pg_isready -h {{ .Values.config.database.host }} -p {{ .Values.config.database.port }} -U {{ .Values.config.database.username }}; do echo waiting for postgresql; sleep 2; done;']
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-database-migration
        image: {{ include "studio.migration.image" . }}
        imagePullPolicy: {{ .Values.backend.migration.image.pullPolicy }}
        env:
          {{- include "studio.keycloak.env" . | nindent 10 }}
          {{- if .Values.backend.environmentVariables.DATABASE_URL.value }}
          - name: DATABASE_URL
            value: {{ .Values.backend.environmentVariables.DATABASE_URL.value | quote }}
          {{- else if .Values.backend.environmentVariables.DATABASE_URL.secret }}
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.backend.environmentVariables.DATABASE_URL.secret.name }}
                key: {{ .Values.backend.environmentVariables.DATABASE_URL.secret.key }}
          {{- end }}
          - name: DB_SSL
            value: {{ .Values.config.database.preferSSL | quote }}
          - name: DB_REJECT_UNAUTHORIZED
            value: {{ .Values.config.database.rejectUnauthorized | quote }}
{{- end }}
