{{- if and .Values.backend.migration.enabled .Values.backend.migration.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio.backend.migration.serviceAccountName" . }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    {{- with .Values.backend.migration.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
