{{- if .Values.studioEnabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "studio.fullname" . }}-backend
  labels:
    {{- include "studio.labels" . | nindent 4 -}}
    app.kubernetes.io/component: studio-backend
    {{- if .Values.deploymentLabels }}
      {{- toYaml .Values.deploymentLabels | nindent 4 }}
    {{- end }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "studio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: studio-backend
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "studio.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: studio-backend
        {{- if .Values.podLabels }}
          {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ include "studio.dnsPolicy" . }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{ toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "studio.backend.serviceAccountName" . }}
      {{- if .Values.backend.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.backend.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-backend
          {{- if .Values.backend.securityContext.enabled }}
          securityContext:
            {{- omit .Values.backend.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: {{ include "studio.backend.image" . }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          {{- if or .Values.backend.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.backend.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if or .Values.backend.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.backend.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
          env:
            {{- include "studio.shared.env" . | nindent 12 }}
            {{- include "studio.keycloak.url" . | nindent 12 }}
            - name: WEB_CLIENT_URL
              value: {{ if .Values.webClient.ingress.hostName }}"{{ .Values.config.connectionType }}://{{ .Values.webClient.ingress.hostName }}"{{ else }}"{{ .Values.config.connectionType }}://{{ .Values.config.ingressHost }}"{{ end }}
            - name: MODEL_TRAINING_MOCK_ENABLED
              value: "false"
            - name: MODEL_RUNNING_MOCK_ENABLED
              value: "false"
            - name: KEYCLOAK_API_GRANT_TYPE
              {{- if .Values.backend.environmentVariables.KEYCLOAK_API_GRANT_TYPE }}
              value: {{ .Values.backend.environmentVariables.KEYCLOAK_API_GRANT_TYPE.value | quote }}
              {{- else }}
              value: "password"
              {{- end }}
            - name: MTS_API_URL
              {{- if .Values.backend.environmentVariables.MTS_API_URL }}
              value: {{ .Values.backend.environmentVariables.MTS_API_URL.value | quote }}
              {{- else }}
              value: "http://rasapro.{{ .Release.Namespace }}:8000"
              {{- end }}
            - name: MRS_API_URL
              {{- if .Values.backend.environmentVariables.MTS_API_URL }}
              value: {{ .Values.backend.environmentVariables.MTS_API_URL.value | quote }}
              {{- else }}
              value: "http://rasapro.{{ .Release.Namespace }}:8000"
              {{- end }}
            {{- range $key, $value := .Values.backend.environmentVariables }}
            {{- if and (not (eq $key "MODEL_TRAINING_MOCK_ENABLED")) (not (eq $key "MTS_API_URL")) (not (eq $key "MRS_API_URL")) }}
            - name: {{ $key | upper }}
              {{- if $value.value }}
              value: {{ $value.value | quote }}
              {{- else if $value.secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secret.name }}
                  key: {{ $value.secret.key }}
              {{- end }}
            {{- end }}
            {{- end }}
          {{- if .Values.backend.envFrom }}
          envFrom:
            {{- toYaml .Values.backend.envFrom | nindent 12 }}
          {{- end }}
      {{- if .Values.backend.additionalContainers }}
        {{- toYaml .Values.backend.additionalContainers | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
