repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: end-of-file-fixer
    -   id: check-yaml

- repo: https://github.com/norwoodj/helm-docs
  rev: v1.2.0
  hooks:
    - id: helm-docs
      args:
        # Make the tool search for charts only under the `example-charts` directory
        - --chart-search-root=helm-charts

        # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
        # A base filename makes it relative to each chart directory found
        - --template-files=README.md.gotmpl
