{{ if and .Values.modelTrainingService.enabled .Values.modelTrainingService.persistence.create -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-training-service-data-pv
  labels:
    name: model-training-service-data-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  {{- if eq .Values.modelTrainingService.persistence.type "local" }}
  local:
    path: {{ .Values.modelTrainingService.persistence.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - {{ .Values.modelTrainingService.persistence.localNodeName }}
  {{- end }}
  {{- if eq .Values.modelTrainingService.persistence.type "nfs" }}
  nfs:
    server: {{ .Values.modelTrainingService.persistence.nfsServer }}
    path: "/"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-training-service-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  selector:
    matchLabels:
      name: model-training-service-data-pv
{{- end }}
