{{- if .Values.web-client.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "studio.serviceAccountName" . }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
  {{- with .Values.web-client.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
