apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-web-client-configmap
data:
  windowVariables: |
    window.API_ENDPOINT = "{{ .Values.config.connectionType }}://{{ include "studio.appHost" . }}/api";
    {{- with .Values.app.webClient.config.MS_API_URL }}
    window.MS_API_URL = {{ . | quote }};
    {{- else }}
    {{- if .Values.rasa.enabled }}
    window.MS_API_URL = "{{ include "studio.modelServiceBaseUrl" . }}";
    {{- else }}
    window.MS_API_URL = "";
    {{- end }}
    {{- end }}
    {{- range $key, $value := .Values.app.webClient.config }}
    {{- if hasPrefix "FEATURE_FLAG_" $key }}
    window.{{ $key }} = {{ $value | quote }};
    {{- end }}
    {{- end }}
    {{- with .Values.app.webClient.config.CURRENT_VERSION_NUMBER }}
    window.CURRENT_VERSION_NUMBER = {{ . | quote | trim }};
    {{- else }}
    window.CURRENT_VERSION_NUMBER = {{ .Values.tag | default .Chart.AppVersion | quote | trim }};
    {{- end }}
