apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-web-client-configmap
data:
  windowVariables: |
    window.API_ENDPOINT = "{{ .Values.config.connectionType }}://{{ include "studio.appHost" . }}/api";
    {{- with .Values.app.webClient.config.MS_API_URL }}
    window.MS_API_URL = {{ . | quote }};
    {{- else }}
    window.MS_API_URL = "{{ include "studio.modelServiceBaseUrl" . }}";
    {{- end }}
    {{- range $key, $value := .Values.app.webClient.config }}
    {{- if hasPrefix "FEATURE_FLAG_" $key }}
    window.{{ $key }} = {{ $value | quote }};
    {{- end }}
    {{- end }}
    window.VOICE_INSPECTOR_ENABLED = {{ .Values.app.webClient.config.VOICE_INSPECTOR_ENABLED | default "false" | quote }};
    window.SILENCE_TIMEOUT_ENABLED = {{ .Values.app.webClient.config.SILENCE_TIMEOUT_ENABLED | default "false" | quote }};
    window.EDIT_SYSTEM_RESPONSES_ENABLED = {{ .Values.app.webClient.config.EDIT_SYSTEM_RESPONSES_ENABLED | default "false" | quote }};
    {{- with .Values.app.webClient.config.CURRENT_VERSION_NUMBER }}
    window.CURRENT_VERSION_NUMBER = {{ . | quote | trim }};
    {{- else }}
    window.CURRENT_VERSION_NUMBER = {{ .Values.tag | default .Chart.AppVersion | quote | trim }};
    {{- end }}
