{{- if .Values.strimzi.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "op-kits.strimzi.kafkaName" . }}
  namespace: {{ include "op-kits.namespace" . }}
  labels:
    {{- include "op-kits.strimzi.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.strimzi.kafka.annotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.strimzi.kafka.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  entityOperator:
    topicOperator:
      {{- toYaml .Values.strimzi.kafka.entityOperator.topicOperator | nindent 6 }}
    userOperator:
      {{- toYaml .Values.strimzi.kafka.entityOperator.userOperator | nindent 6 }}
  kafka:
    {{- with .Values.strimzi.kafka.image }}
    # Container image
    image: {{ . | quote }}
    {{- end }}
    listeners:
      {{- toYaml .Values.strimzi.kafka.listeners | nindent 6 }}
    config:
      {{- toYaml .Values.strimzi.kafka.config | nindent 6 }}
    {{- with .Values.strimzi.kafka.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if or .Values.tolerations .Values.affinity }}
    template:
      pod:
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}
{{- end }}
