---
name: Feature request
description: Suggest an idea for this project
title: "[FEATURE] "
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: What Problem are you trying to solve? (Link any issues here)
      description: A clear and concise description of what the problem is. Please describe.
      placeholder: |
        Ex. I'm always frustrated when [...]
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Related helm chart
      description: You may select more than one.
      multiple: true
      options:
        - rasa-pro
        - rasa-studio
        - other
    validations:
      required: true

  - type: textarea
    attributes:
      label: What does your ideal solution look like?
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any other implementation suggestions for this feature?
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
