{{- if and .Values.strimzi.enabled .Values.strimzi.nodePools.brokers.enabled }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ include "op-kits.strimzi.kafkaName" . }}-brokers
  namespace: {{ include "op-kits.namespace" . }}
  labels:
    {{- include "op-kits.strimzi.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ include "op-kits.strimzi.kafkaName" . }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  roles:
    {{- toYaml .Values.strimzi.nodePools.brokers.roles | nindent 4 }}
  replicas: {{ .Values.strimzi.nodePools.brokers.replicas }}
  {{- $storage := .Values.strimzi.nodePools.brokers.storage }}
  storage:
    type: {{ $storage.type }}
    {{- if eq $storage.type "jbod" }}
    volumes:
      {{- toYaml $storage.volumes | nindent 6 }}
    {{- else if eq $storage.type "ephemeral" }}
    {{- with $storage.sizeLimit }}
    sizeLimit: {{ . }}
    {{- end }}
    {{- else if eq $storage.type "persistent-claim" }}
    size: {{ $storage.size }}
    class: {{ $storage.class }}
    deleteClaim: {{ $storage.deleteClaim }}
    {{- end }}
  {{- with .Values.strimzi.nodePools.brokers.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.tolerations .Values.affinity }}
  template:
    pod:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
