{{- if and .Values.strimzi.enabled .Values.strimzi.nodePools.controllers.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ include "op-kits.strimzi.kafkaName" . }}-controllers
  namespace: {{ include "op-kits.namespace" . }}
  labels:
    {{- include "op-kits.strimzi.labels" . | nindent 4 }}
    strimzi.io/cluster: {{ include "op-kits.strimzi.kafkaName" . }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  roles:
    {{- toYaml .Values.strimzi.nodePools.controllers.roles | nindent 4 }}
  replicas: {{ .Values.strimzi.nodePools.controllers.replicas }}
  storage:
    type: {{ .Values.strimzi.nodePools.controllers.storage.type }}
    size: {{ .Values.strimzi.nodePools.controllers.storage.size }}
    class: {{ .Values.strimzi.nodePools.controllers.storage.class }}
    deleteClaim: {{ .Values.strimzi.nodePools.controllers.storage.deleteClaim }}
  {{- with .Values.strimzi.nodePools.controllers.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.tolerations .Values.affinity }}
  template:
    pod:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
