{{- if .Values.backend.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "studio.fullname" . }}-database-migration
  labels:
    {{- include "studio.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "studio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: {{ include "studio.fullname" . }}-database-migration
        image: "{{ .Values.backend.migration.image.repository }}:{{ .Values.backend.migration.image.tag }}"
        env:
        {{- if .Values.backend.environmentVariables.DATABASE_URL.value }}
        - name: DATABASE_URL
          value: {{ .Values.backend.environmentVariables.DATABASE_URL.value | quote }}
        {{- else if .Values.backend.environmentVariables.DATABASE_URL.secret }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.environmentVariables.DATABASE_URL.secret.name }}
              key: {{ .Values.backend.environmentVariables.DATABASE_URL.secret.key }}
        {{- end }}
{{- end }}
