{{- if .Values.modelService.running.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: model-running-service
  labels:
    {{- include "studio.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.modelService.running.orchestrator.service.port }}
      targetPort: {{ .Values.modelService.running.orchestrator.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "modelRunningService.selectorLabels" . | nindent 4 }}
{{- end }}
