{{- if and .Values.modelService.running.enabled .Values.modelService.running.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "modelRunningService.serviceAccountName" . }}
  namespace: {{ .Values.modelService.namespace | default .Release.Namespace }}
  labels:
    {{- include "studio.labels" . | nindent 4 }}
  {{- with .Values.modelService.running.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "modelRunningService.serviceAccountName" . }}-role
  namespace: {{ .Values.modelService.namespace | default .Release.Namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods
  - pods/log
  - pods/status
  - services
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  - jobs/status
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "modelRunningService.serviceAccountName" . }}-role-binding
  namespace: {{ .Values.modelService.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "modelRunningService.serviceAccountName" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "modelRunningService.serviceAccountName" . }}
  namespace: {{ .Values.modelService.namespace | default .Release.Namespace }}
{{- end }}
