{{- if and .Values.rasaProServices.enabled .Values.rasaProServices.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rasa.rasaProServices.serviceAccountName" . }}
  labels:
    {{- include "rasa.labels" . | nindent 4 }}
  {{- with .Values.rasaProServices.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
