{{- include "rasa.validatePodDisruptionBudget" . -}}
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rasa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rasa.labels" . | nindent 4 }}
  {{- with .Values.podDisruptionBudget.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rasa.selectorLabels" . | nindent 6 }}
{{- end }}
