# Default values for studio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

############################
# THIS IS WORK IN PROGRESS #
############################

# -- (string) Override name of app
nameOverride: ""
# -- (string) Override the full qualified app name
fullnameOverride: ""

# -- Repository pull secrets
imagePullSecrets:
  []
  # - name: regcred

# Studio Backend component specific configuration
backend:
  # -- Specifies number of replicas
  replicaCount: 1
  # -- Define image settings
  image:
    # -- Specifies image repository
    repository: "europe-west3-docker.pkg.dev/rasa-releases/studio-backend/studio-backend"
    # -- Specifies image pull policy
    pullPolicy: IfNotPresent
    # -- Specifies image tag
    ## Overrides the image tag whose default is the chart appVersion.
    tag: "v0.1.0-latest"

  # -- Define environment variables for deployment
  # Example: Specify the string value for variables
  #   value: my-value
  # Example: Specify the value for variables sourced from a Secret.
  #   secret:
  #     name: my-secret
  #     key: my-secret-key
  # NOTE: Helm will return an error if environment variable does not have `value` or `secret` provided.
  environmentVariables:
    DATABASE_URL:
      value: ""
      # secret:
      #   name:
      #   key:
    KEYCLOAK_URL:
      value: ""
    KEYCLOAK_REALM:
      value: "rasa-local-dev"
    KEYCLOAK_API_CLIENT_ID:
      value: "admin-cli"
    KEYCLOAK_API_USERNAME:
      value: ""
    KEYCLOAK_API_PASSWORD:
      value: ""
    KEYCLOAK_API_GRANT_TYPE:
      value: "password"

  # -- Define service account
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    ## If not set and create is true, a name is generated using the fullname template
    name: ""

  # -- Annotations to add to the pod
  podAnnotations:
    {}
    # container.apparmor.security.beta.kubernetes.io/studio-backend: runtime/default

  # -- Define pod security context
  podSecurityContext:
    enabled: true
    # fsGroup: 2000

  # -- Define security context that allows you to overwrite the pod-level security context
  securityContext:
    enabled: true
    # privileged: false
    # allowPrivilegeEscalation: false
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
    # seccompProfile:
    #   type: RuntimeDefault

  # -- Define service
  service:
    # -- Specify service type
    type: ClusterIP
    # -- Specify service port
    port: 80
    targetPort: 4000

  # -- Override default liveness probe settings
  livenessProbe:
    enabled: true
    httpGet:
      path: /api/health
      port: 4000
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 6

  # -- Override default readiness probe settings
  readinessProbe:
    enabled: true
    httpGet:
      path: /api/health
      port: 4000
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 6

  # -- Define Studio Database Migration job settings
  migration:
    # -- Specifies whether a database migration job should be created
    enable: true
    # -- Specifies which image database migration job should use
    image:
      # -- Specifies the repository of the image
      repository: "europe-west3-docker.pkg.dev/rasa-releases/studio-database-migration/studio-database-migration"
      # -- Specifies the tag of the image
      tag: "v0.1.0-latest"

  # -- Configure the ingress resource that allows you to access the deployment installation.
  ## ref: http://kubernetes.io/docs/user-guide/ingress/
  ingress:
    # -- Specifies whether an ingress service should be created
    enabled: true
    # -- Specifies the ingress className to be used
    className: ""
    # -- Labels to add to the ingress
    labels: {}
    # -- Annotations to add to the ingress
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # -- Specifies the hosts for this ingress
    hosts:
      - host: chart-example.local
        paths:
          - path: /api
            pathType: Prefix
        extraPaths: []
    # -- Spefices the TLS configuration for ingress
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  # -- Specifies the resources limits and requests
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- Specifies the HPA settings
  autoscaling:
    # -- Specifies whether autoscaling should be enabled
    enabled: false
    # -- Specifies the minimum number of replicas
    minReplicas: 1
    # -- Specifies the maximum number of replicas
    maxReplicas: 100
    # -- Specifies the target CPU/Memory utilization percentage
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # -- Allow the deployment to be scheduled on selected nodes
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Allow the deployment to schedule using affinity rules
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# Studio Web Client component specific configuration
webClient:
  # -- Specifies number of replicas
  replicaCount: 1
  # -- Define image settings
  image:
    # -- Specifies image repository
    repository: "europe-west3-docker.pkg.dev/rasa-releases/studio-web-client/studio-web-client"
    # -- Specifies image pull policy
    pullPolicy: IfNotPresent
    # -- Specifies image tag
    ## Overrides the image tag whose default is the chart appVersion.
    tag: "v0.1.0-latest"

  # -- Define environment variables for deployment
  environmentVariables:
    API_ENDPOINT: ""
    KEYCLOAK_URL: ""
    KEYCLOAK_REALM: "rasa-local-dev"
    KEYCLOAK_CLIENT_ID: "studio-local"

  # -- Define service account
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    ## If not set and create is true, a name is generated using the fullname template
    name: ""

  # -- Annotations to add to the pod
  podAnnotations:
    {}
    # container.apparmor.security.beta.kubernetes.io/studio-web-client: runtime/default

  # -- Define pod security context
  podSecurityContext:
    enabled: true
    # fsGroup: 2000

  # -- Define security context that allows you to overwrite the pod-level security context
  securityContext:
    enabled: true
    # privileged: false
    # allowPrivilegeEscalation: false
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
    # seccompProfile:
    #   type: RuntimeDefault

  # -- Define service
  service:
    # -- Specify service type
    type: ClusterIP
    # -- Specify service port
    port: 80
    targetPort: 80

  # -- Override default liveness probe settings
  livenessProbe:
    enabled: true
    httpGet:
      path: /
      port: http
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 6

  # -- Override default readiness probe settings
  readinessProbe:
    enabled: true
    httpGet:
      path: /
      port: http
      scheme: HTTP
    initialDelaySeconds: 15
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 6

  # -- Configure the ingress resource that allows you to access the deployment installation.
  ## ref: http://kubernetes.io/docs/user-guide/ingress/
  ingress:
    # -- Specifies whether an ingress service should be created
    enabled: true
    # -- Specifies the ingress className to be used
    className: ""
    # -- Labels to add to the ingress
    labels: {}
    # -- Annotations to add to the ingress
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # -- Specifies the hosts for this ingress
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
        extraPaths: []
    # -- Spefices the TLS configuration for ingress
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  # -- Specifies the resources limits and requests
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- Allow the deployment to be scheduled on selected nodes
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Allow the deployment to schedule using affinity rules
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# Studio Event Ingestion component specific configuration
eventIngestion:
  # -- Specifies number of replicas
  replicaCount: 1
  # -- Define image settings
  image:
    # -- Specifies image repository
    repository: "europe-west3-docker.pkg.dev/rasa-releases/studio-event-ingestion/studio-event-ingestion"
    # -- Specifies image pull policy
    pullPolicy: IfNotPresent
    # -- Specifies image tag
    ## Overrides the image tag whose default is the chart appVersion.
    tag: "v0.1.0-latest"

  # -- Define environment variables for deployment
  # Example: Specify the string value for variables
  #   value: my-value
  # Example: Specify the value for variables sourced from a Secret.
  #   secret:
  #     name: my-secret
  #     key: my-secret-key
  # NOTE: Helm will return an error if environment variable does not have `value` or `secret` provided.
  environmentVariables:
    DATABASE_URL:
      value: ""
    SECURITY_PROTOCOL:
      value: "SASL_SSL"
    SASL_MECHANISM:
      value: "SCRAM-SHA-256"
    SASL_USERNAME:
      value: ""
    SASL_PASSWORD:
      value: ""
    KAFKA_BROKER_ADDRESS:
      value: ""
    KAFKA_TOPIC:
      value: ""
    KAFKA_DLQ_TOPIC:
      value: ""
    KAFKA_CLIENT_ID:
      value: "kafka-python-rasa"
    GROUP_ID:
      value: ""

  # -- Define service account
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    ## If not set and create is true, a name is generated using the fullname template
    name: ""

  # -- Annotations to add to the pod
  podAnnotations:
    {}
    # container.apparmor.security.beta.kubernetes.io/studio-event-ingestion: runtime/default

  # -- Define pod security context
  podSecurityContext:
    enabled: true
    # fsGroup: 2000

  # -- Define security context that allows you to overwrite the pod-level security context
  securityContext:
    enabled: true
    # privileged: false
    # allowPrivilegeEscalation: false
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
    # seccompProfile:
    #   type: RuntimeDefault

  # -- Specifies the resources limits and requests
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # -- Specifies the HPA settings
  autoscaling:
    # -- Specifies whether autoscaling should be enabled
    enabled: false
    # -- Specifies the minimum number of replicas
    minReplicas: 1
    # -- Specifies the maximum number of replicas
    maxReplicas: 100
    # -- Specifies the target CPU/Memory utilization percentage
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  # -- Allow the deployment to be scheduled on selected nodes
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Allow the deployment to schedule using affinity rules
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# Studio Keycloak component specific configuration
keycloak:
  # -- Specifies number of replicas
  replicaCount: 1
  # -- Define image settings
  image:
    # -- Specifies image repository
    repository: "europe-west3-docker.pkg.dev/rasa-releases/studio-keycloak/studio-keycloak"
    # -- Specifies image pull policy
    pullPolicy: IfNotPresent
    # -- Specifies image tag
    ## Overrides the image tag whose default is the chart appVersion.
    tag: "v0.1.0-latest"

  # -- Define service account
  serviceAccount:
    # -- Specifies whether a service account should be created
    create: false
    # -- Annotations to add to the service account
    annotations: {}
    # -- The name of the service account to use.
    ## If not set and create is true, a name is generated using the fullname template
    name: ""

  # -- Annotations to add to the pod
  podAnnotations:
    {}
    # container.apparmor.security.beta.kubernetes.io/studio-keycloak: runtime/default

  # -- Define pod security context
  podSecurityContext:
    enabled: true
    # fsGroup: 2000

  # -- Define security context that allows you to overwrite the pod-level security context
  securityContext:
    enabled: true
    # privileged: false
    # allowPrivilegeEscalation: false
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
    # seccompProfile:
    #   type: RuntimeDefault

  # -- Define service
  service:
    # -- Specify service type
    type: ClusterIP
    # -- Specify service port
    port: 80
    targetPort: 8080

  # -- Override default liveness probe settings
  livenessProbe:
    enabled: true
    httpGet:
      path: /auth
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 6

  # -- Override default readiness probe settings
  readinessProbe:
    enabled: true
    httpGet:
      path: /auth
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 5
    failureThreshold: 6

  # -- Configure the ingress resource that allows you to access the deployment installation.
  ## ref: http://kubernetes.io/docs/user-guide/ingress/
  ingress:
    # -- Specifies whether an ingress service should be created
    enabled: true
    # -- Specifies the ingress className to be used
    className: ""
    # -- Labels to add to the ingress
    labels: {}
    # -- Annotations to add to the ingress
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    # -- Specifies the hosts for this ingress
    hosts:
      - host: chart-example.local
        paths:
          - path: /auth
            pathType: Prefix
        extraPaths: []
    # -- Spefices the TLS configuration for ingress
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  # -- Specifies the resources limits and requests
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi

  # -- Allow the deployment to be scheduled on selected nodes
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
  nodeSelector: {}

  # -- Tolerations for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []

  # -- Allow the deployment to schedule using affinity rules
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}

# Network policy settings
networkPolicy:
  # -- Specifies whether to enable network policies
  enabled: false
  # -- Specifies whether to apply denyAll network policy
  denyAll: false
  # -- Allow for traffic from a given CIDR - it's required in order to make kubelet able to run live and readiness probes
  nodeCIDR: []
  #  - ipBlock:
  #      cidr: 0.0.0.0/0

global:
  # -- additionalDeploymentLabels can be used to map organizational structures onto system objects
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
  additionalDeploymentLabels: {}

# -- Controls whether the pod may use the node network namespace
hostNetwork: false

# -- Specifies Pod's DNS policy
## ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
dnsPolicy: ""

# -- Specifies Pod's DNS condig
## ref: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config
dnsConfig:
  {}
  # options:
  # - name: ndots
  #   value: "1"
