apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-web-client-configmap
data:
  windowVariables: |
    window.API_ENDPOINT: {{ .Values.webClient.environmentVariables.API_ENDPOINT }}
    window.KEYCLOAK_URL: {{ .Values.webClient.environmentVariables.KEYCLOAK_URL }}
    window.KEYCLOAK_REALM: {{ .Values.webClient.environmentVariables.KEYCLOAK_REALM }}
    window.KEYCLOAK_CLIENT_ID: {{ .Values.webClient.environmentVariables.KEYCLOAK_CLIENT_ID }}
