apiVersion: v1
kind: ConfigMap
metadata:
  name: studio-web-client-configmap
data:
  windowVariables: |
    window.API_ENDPOINT: example
    window.KEYCLOAK_URL: example
    window.KEYCLOAK_REALM: example
    window.KEYCLOAK_CLIENT_ID: example
