{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.denyAll }}
apiVersion: {{ template "networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "studio.fullname" . }}-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
