{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.nodeCIDR }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-egress-from-kubelet-to-studio-app
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/component: studio-app
  egress:
    - to:
    {{- toYaml .Values.networkPolicy.nodeCIDR | nindent 6 }}
  ingress:
    - from:
    {{- toYaml .Values.networkPolicy.nodeCIDR | nindent 6 }}
      ports:
      - protocol: TCP
        port: {{ .Values.app.service.port }}
{{- end }}
