apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
metadata:
  name: embedded-cluster-config
spec:
  version: 2.7.1+k8s-1.31
  domains:
    # Your proxy registry custom domain
    proxyRegistryDomain: registry.rasa.com
    # Your app service custom domain
    replicatedAppDomain: replicated.rasa.com
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          api:
            extraArgs:
              service-node-port-range: 80-32767
  extensions:
    helm:
      repositories:
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
      - name: cnpg-operator
        url: https://cloudnative-pg.github.io/charts
      - name: strimzi-operator
        url: https://strimzi.io/charts/
      charts:
      - name: ingress-nginx
        chartname: ingress-nginx/ingress-nginx
        namespace: ingress-nginx
        version: "4.12.1"
        values: |
          controller:
            service:
              type: NodePort
              nodePorts:
                http: "80"
                https: "443"
            image:
              digest: ""
              digestChroot: ""
            admissionWebhooks:
              patch:
                image:
                  digest: ""
      - name: cnpg-operator
        chartname: cloudnativepg/cloudnativepg
        namespace: cnpg-system
        version: "1.10.0"
      - name: strimzi-operator
        chartname: strimzi/strimzi-kafka-operator
        namespace: strimzi-system
        version: "0.47.0"
        values: |
          watchAnyNamespace: true
