apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: ingress-nginx
spec:
  exclude: 'repl{{ ConfigOptionNotEquals `install_nginx` `on_kubernetes` }}'
  chart:
    name: ingress-nginx
    chartVersion: 4.10.1
  
  releaseName: ingress-nginx
  namespace: ingress-nginx
  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    imagePullSecrets:
      - '{{repl ImagePullSecretName }}'
    controller:
      image:
        registry: registry.k8s.io
        image: ingress-nginx/controller
        tag: "v1.10.1"
      admissionWebhooks:
        patch:
          image:
            registry: registry.k8s.io
            image: ingress-nginx/kube-webhook-certgen
            tag: v1.4.1
