apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: ingress-nginx
spec:
  exclude: true
  chart:
    name: ingress-nginx
    chartVersion: 4.11.1
  
  releaseName: ingress-nginx
  namespace: ingress-nginx
  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    imagePullSecrets:
      - name: '{{repl ImagePullSecretName }}'
    controller:
      image:
        registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "registry.rasa.com"}}'
        # image: ingress-nginx/controller
        image: '{{repl HasLocalRegistry | ternary LocalRegistryNamespace (print "proxy/" (LicenseFieldValue "appSlug") "/europe-west3-docker.pkg.dev/rasa-releases/dependencies" ) }}/controller'
        tag: "v1.11.1"
        digest: ""
        digestChroot: ""
      admissionWebhooks:
        patch:
          image:
            registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "registry.rasa.com"}}'
            # image: ingress-nginx/kube-webhook-certgen
            image: '{{repl HasLocalRegistry | ternary LocalRegistryNamespace (print "proxy/" (LicenseFieldValue "appSlug") "/europe-west3-docker.pkg.dev/rasa-releases/dependencies" ) }}/kube-webhook-certgen'
            tag: v1.4.1
            digest: ""
