apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: op-kits
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: op-kits
    chartVersion: 0.1.2

  releaseName: op-kits
  namespace: studio
  weight: 5

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    cloudnativepg:
      enabled: true
      cluster:
        imageName: "ghcr.io/cloudnative-pg/postgresql:16"
        instances: 1
        storage:
          size: 10Gi
          storageClass: openebs-hostpath
        bootstrap:
          initdb:
            database: studio
            owner: studiouser
    strimzi:
      enabled: true
      kafka:
        image: "quay.io/strimzi/kafka:0.47.0-kafka-4.0.0"
      nodePools:
        controllers:
          storage:
            class: openebs-hostpath
            size: 10Gi
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "2Gi"
        brokers:
          storage:
            volumes:
              - id: 0
                type: "persistent-claim"
                size: "20Gi"
                class: "openebs-hostpath"
                deleteClaim: true
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "750m"
              memory: "2Gi"
      topics:
        rasaEvents:
          enabled: true
          name: '{{repl ConfigOption "kafka_topic" }}'
          partitions: 1
          replicas: 1
          config:
            retention.ms: 604800000  # 7 days
            cleanup.policy: "delete"

        rasaEventsDlq:
          enabled: true
          name: '{{repl ConfigOption "kafka_dlq_topic" }}'
          partitions: 1
          replicas: 1
          config:
            retention.ms: 1209600000  # 14 days
            cleanup.policy: "delete"

        rasaCoreEvents:
          enabled: true
          name: '{{repl ConfigOption "rasa_core_events_topic" }}'
          partitions: 1
          replicas: 1
          config:
            retention.ms: 604800000  # 7 days
            cleanup.policy: "delete"

        rasaAssistant:
          enabled: true
          name: '{{repl ConfigOption "rasa_assistant_topic" }}'
          partitions: 1
          replicas: 1
          config:
            retention.ms: 604800000  # 7 days
            cleanup.policy: "delete"
      users:
        app:
          enabled: true
          name: "studio-app"
          authentication:
            type: "scram-sha-512"
            password:
              secretName: "studio-secrets"
              secretKey: "KAFKA_SASL_PASSWORD"
    valkey:
      enabled: false
