apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: postgresql
spec:
  exclude: true
  chart:
    name: postgresql
    chartVersion: 16.3.0
  
  releaseName: postgresql
  namespace: postgresql
  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    global:
      security: 
        allowInsecureImages: true
      postgresql:
        auth:
          postgresPassword: '{{repl ConfigOption "database_password" }}'
          username: '{{repl ConfigOption "database_username" }}'
          password: '{{repl ConfigOption "database_password" }}'
          database: studio
    image:
      registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "registry.rasa.com"}}'
      repository: '{{repl HasLocalRegistry | ternary LocalRegistryNamespace (print "proxy/" (LicenseFieldValue "appSlug") "/europe-west3-docker.pkg.dev/rasa-releases/dependencies" ) }}/postgresql'
      tag: '{{repl ConfigOption "postgresql_image_tag" }}'
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets:
        - '{{repl ImagePullSecretName }}'
