apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: redis
spec:
  exclude: 'repl{{ ConfigOptionEquals `rasa_platform_deploy` `studio` }}'
  chart:
    name: redis
    chartVersion: 20.0.3

  releaseName: redis
  namespace: redis
  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    global:
      redis:
        password: '{{repl ConfigOption "redis_password" }}'
    image:
      registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "registry.rasa.com"}}'
      repository: '{{repl HasLocalRegistry | ternary LocalRegistryNamespace (print "proxy/" (LicenseFieldValue "appSlug") "/europe-west3-docker.pkg.dev/rasa-releases/dependencies" ) }}/redis'
      tag: 7.4.0-debian-12-r2
      digest: ""
      pullPolicy: IfNotPresent
      pullSecrets:
        - '{{repl ImagePullSecretName }}'
    replica:
      replicaCount: 1
