apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: studio
spec:
  title: Rasa Studio
  icon: https://info.rasa.com/hubfs/Rasa_January2020/Images/rasa-logo-square-ef3444fc36faec97ae8bd7bfb568996d.svg
  requireMinimalRBACPrivileges: false
  allowRollback: true
  minKotsVersion: 1.79.0
  graphs:
    - title: User Signups
      query: 'sum(user_signup_events_total)'
    # Disk Usage, CPU Usage, and Memory Usage below are the default graphs
    - title: Disk Usage
      queries:
        - query: 'sum((node_filesystem_size_bytes{job="node-exporter",fstype!="",instance!=""} - node_filesystem_avail_bytes{job="node-exporter", fstype!=""})) by (instance)'
          legend: 'Used: {{ instance }}'
        - query: 'sum((node_filesystem_avail_bytes{job="node-exporter",fstype!="",instance!=""})) by (instance)'
          legend: 'Available: {{ instance }}'
      yAxisFormat: bytes
    - title: CPU Usage
      query: 'sum(rate(container_cpu_usage_seconds_total{namespace="{{repl Namespace}}",container!="POD",pod!=""}[5m])) by (pod)'
      legend: '{{ pod }}'
    - title: Memory Usage
      query: 'sum(container_memory_usage_bytes{namespace="{{repl Namespace}}",container!="POD",pod!=""}) by (pod)'
      legend: '{{ pod }}'
      yAxisFormat: bytes
  additionalNamespaces:
    - "ingress-nginx"
    - "postgresql"
    - "kafka"
    - "studio"
  statusInformers:
    - studio/deployment/studio-backend
    - studio/deployment/studio-keycloak
    - studio/deployment/studio-event-ingestion
    - studio/deployment/studio-web-client
    - studio/deployment/model-running-service-orchestrator
    - studio/statefulset/model-running-service-consumer
    - studio/deployment/model-training-service-orchestrator
    - studio/statefulset/model-training-service-consumer
    - studio/persistentvolumeclaims/model-running-service-data-pvc-studio
    - studio/persistentvolumeclaims/model-training-service-data-pvc-studio
    - studio/deployment/nginx-reverse-proxy
  additionalImages:
    - europe-west3-docker.pkg.dev/rasa-releases/rasa-pro/rasa-pro:3.10.4-latest
