apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: studio
spec:
  title: Rasa Studio
  icon: https://info.rasa.com/hubfs/Rasa_January2020/Images/rasa-logo-square-ef3444fc36faec97ae8bd7bfb568996d.svg
  requireMinimalRBACPrivileges: false
  allowRollback: true
  minKotsVersion: 1.119.0
  additionalNamespaces:
    - "ingress-nginx"
    - "postgresql"
    - "kafka"
    - "studio"
  statusInformers:
    - studio/deployment/studio-backend
    - studio/deployment/studio-keycloak
    - studio/deployment/studio-event-ingestion
    - studio/deployment/studio-web-client
    - studio/deployment/rasapro
  additionalImages:
    - europe-west3-docker.pkg.dev/rasa-releases/rasa-pro/rasa-pro:3.11.3
