{{- if .Values.networkPolicy.enabled }}
apiVersion: {{ template "networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "rasa.fullname" . }}-allow-dns-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
{{- end }}
