{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rasa.fullname" . }}-allow-egress-http-https
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rasa.fullname" . }}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
{{- end }}
