{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.nodeCIDR }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "rasa.fullname" . }}-kubelet-access
  namespace: {{ .Release.Namespace }}
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rasa.name" . }}
  egress:
    - to:
    {{- toYaml .Values.networkPolicy.nodeCIDR | nindent 6 }}
  ingress:
    - from:
    {{- toYaml .Values.networkPolicy.nodeCIDR | nindent 6 }}
      ports:
      - protocol: TCP
        port: {{ .Values.rasa.service.port }}
{{- end }}
