{{- if and .Values.networkPolicy.enabled .Values.networkPolicy.rabbitmqAllowEgressIngress.enabled }}
apiVersion: {{ template "networkPolicy.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: {{ include "rasa.fullname" . }}-rabbitmq-https-kubernetes-api
spec:
  podSelector:
    matchLabels:
      {{- .Values.networkPolicy.rabbitmqAllowEgressIngress.matchLabels | toYaml | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - ports:
      - protocol: TCP
        port: 8443
      - protocol: TCP
        port: 443
---
{{- end }}
