apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-environment
  namespace: {{ .Release.Namespace }}
data:
  RASA_MODEL_SERVER_BASE_URL: "{{ include "studio.modelServiceTalkUrl" . }}"
  CORS_ORIGINS: "{{ include "studio.webClientUrl" . }}"
