{{- if .Values.rasa.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rasa.fullname" . }}
  labels:
    {{- include "rasa.labels" . | nindent 4 }}
    {{- if .Values.deploymentLabels }}
      {{- toYaml .Values.deploymentLabels | nindent 4 }}
    {{- end }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.rasa.autoscaling.enabled }}
  replicas: {{ .Values.rasa.replicaCount }}
  {{- end }}
  {{- with .Values.hostAliases }}
  hostAliases:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.rasa.strategy }}
  strategy:
    {{- toYaml .Values.rasa.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rasa.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/rasa/configmap.yaml") . | sha256sum }}
      {{- if .Values.rasa.podAnnotations }}
        {{- toYaml .Values.rasa.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rasa.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
          {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ include "rasa.dnsPolicy" . }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{ toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rasa.serviceAccountName" . }}
      {{- if .Values.rasa.podSecurityContext.enabled }}
      securityContext:
        {{- omit .Values.rasa.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.rasa.initContainers }}
      initContainers:
        {{- toYaml .Values.rasa.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: rasa
          {{- if .Values.rasa.containerSecurityContext.enabled }}
          securityContext:
            {{- omit .Values.rasa.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ .Values.rasa.image.repository }}:{{ .Values.rasa.image.tag }}"
          imagePullPolicy: {{ .Values.rasa.image.pullPolicy }}
          {{- if .Values.rasa.args }}
          args:
            {{- toYaml .Values.rasa.args | nindent 12 }}
          {{- else if .Values.rasa.settings.useDefaultArgs }}
          args:
            {{- include "rasa.defaultArgs" . | nindent 12 }}
          {{- if .Values.rasa.additionalArgs }}
            {{- toYaml .Values.rasa.additionalArgs | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if .Values.rasa.command }}
          command:
            {{- toYaml .Values.rasa.command | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.rasa.service.port }}
              protocol: TCP
          {{- if .Values.rasa.overrideEnv }}
          env:
            {{- toYaml .Values.rasa.overrideEnv | nindent 12 }}
          {{- else }}
          env:
            {{- include "rasa.containers.env" . | nindent 12 }}
          {{- end }}
          {{- if .Values.rasa.envFrom }}
          envFrom:
            {{- toYaml .Values.rasa.envFrom | nindent 12 }}
          {{- end }}
          {{- if or .Values.rasa.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.rasa.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if or .Values.rasa.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.rasa.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.rasa.resources | nindent 12 }}
          volumeMounts:
            {{- include "rasa.containers.volumeMounts" . | nindent 12 }}
          {{- if .Values.rasa.volumeMounts }}
            {{- toYaml .Values.rasa.volumeMounts | nindent 12 }}
          {{- end }}
      {{- if .Values.rasa.additionalContainers }}
        {{- toYaml .Values.rasa.additionalContainers | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "rasa.containers.volumes" . | nindent 8 }}
      {{- if .Values.rasa.volumes }}
        {{- toYaml .Values.rasa.volumes | nindent 8 }}
      {{- end }}
      {{- with .Values.rasa.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rasa.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rasa.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
