apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-redis-configmap
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  redis-config: |
    maxmemory 5mb
    maxmemory-policy allkeys-lru