{{- if .Values.redis.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm.fullname" . }}-redis-hpa
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helm.fullname" . }}
  minReplicas: {{ .Values.redis.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.redis.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.redis.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.redis.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.redis.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.redis.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
