{{- if .Values.redis.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm.serviceAccountName" . }}-redis-sa
  labels:
    {{- include "helm.labels" . | nindent 4 }}
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
