# Basic values for rasa.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
  # - name: regcred

# -- rasaProLicense is license key for Rasa Pro.
rasaProLicense:
  secretName: "rasa-secrets"
  secretKey: "rasaProLicense"

# Rasa Open Source
rasa:
  enabled: true
  replicaCount: 1
  image:
    repository: "europe-west3-docker.pkg.dev/rasa-releases/rasa-pro/rasa-pro"
    pullPolicy: IfNotPresent
    tag: "3.8.0-latest"
  settings:
    port: 5005
    scheme: http
    enableApi: true
    mountDefaultConfigmap: true
    mountModelsVolume: true
    credentials:
      rest:
    endpoints:
      action_endpoint:
        url: "http://my-action-server.actions.svc.cluster.local:5055/webhook"
      tracker_store:
        type: redis
        url: redis-lockstore-master
        port: 6379
        db: 1
        password: ${REDIS_PASSWORD}
      event_broker:
        type: kafka
        url: rasa-kafka-bootstrap.example-pro.svc:9092
        security_protocol: SASL_SSL
        sasl_mechanism: PLAIN
        sasl_username: ${KAFKA_USER}
        sasl_password: ${KAFKA_PASSWORD}
  service:
    type: ClusterIP
    port: 5005
    targetPort: 5005
  additionalEnv:
    - name: KAFKA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kafka-secrets
          key: password
    - name: KAFKA_USER
      valueFrom:
        secretKeyRef:
          name: kafka-secrets
          key: username
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: redis-secrets
          key: password
