{{- if and .Values.duckling.enabled .Values.duckling.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rasa.duckling.serviceAccountName" . }}
  labels:
    {{- include "rasa.labels" . | nindent 4 }}
  {{- with .Values.duckling.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
