name: Backup to S3

on:
  push:
    branches:
      - sec-217
#   schedule:
#     - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0

      - name: Backup repository to S3
        uses: peter-evans/s3-backup@59efd330705d92805a44894668b6cf5c10dc740e
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          MIRROR_TARGET: github-backups-dr/rasa-helm-charts
        with:
          args: --overwrite --remove
