name: Release Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - '!replicated/**'
  workflow_dispatch: {}

permissions:
  contents: write       # needed for releases + committing index.yaml
  pull-requests: write  # needed to open PRs

jobs:
  release-charts:
    name: Release Helm Charts to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      # 1) Run chart-releaser: upload packages to GitHub Releases,
      #    generate index.yaml into a temp branch (not main)
      - name: Package & upload charts
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_SKIP_PAGES: "true"               # don't try to commit index.yaml
          CR_GENERATE_RELEASE_NOTES: "true"
          CR_SKIP_EXISTING: "true"

      # 2) Generate a new index.yaml locally from all releases
      - name: Generate updated index.yaml
        run: |
          mkdir -p charts
          helm repo index charts \
            --url "https://github.com/${{ github.repository }}/releases/download"

      # 3) Open a PR with the updated index.yaml
      - name: Create PR for index.yaml
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(helm): update charts/index.yaml"
          title: "chore(helm): update Helm index"
          branch: ci/update-helm-index
          base: main
          body: |
            ## 📦 Helm Repository Index Update

            This PR updates the Helm repository index with newly released charts.
            Charts are available from GitHub Releases.

            Once merged, `https://<your-domain>/charts` will include the latest versions.
          add-paths: |
            charts/index.yaml
