name: Release Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - '!replicated/**'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "rasabot"
          git config user.email "rasabot@rasa.io"

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          version: v3.15.2

      - name: Release charts (GitHub Releases + index.yaml to main)
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.CHART_RELEASER_PAT }}
          CR_PAGES_BRANCH: main
          CR_PAGES_INDEX_PATH: charts/index.yaml
          CR_GENERATE_RELEASE_NOTES: "true"
          CR_SKIP_EXISTING: "true"
