name: Release Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - '!replicated/**'
  workflow_dispatch: {}

permissions:
  contents: write                  # needed for releases + committing index.yaml
  id-token: write
  pull-requests: read
  issues: read

jobs:
  release-charts:
    name: Release Helm Charts to GitHub Pages
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          version: v3.15.2

      - name: Release charts (GitHub Releases + index.yaml)
        uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Keep Pages on 'main' and commit ONLY the index file to a subpath
          CR_PAGES_BRANCH: main
          CR_PAGES_INDEX_PATH: charts/index.yaml
          # GitHub auto-generated release notes
          CR_GENERATE_RELEASE_NOTES: "true"
          # Skip existing releases (normal behavior)
          CR_SKIP_EXISTING: "true"

      - name: Notify Slack of successful release 💬
        if: success()
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          channel-id: 'C0351QXJ5CP'
          slack-message: "🚀 New Helm Charts have been released to GitHub Pages!"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack of unsuccessful release ⛔️
        if: failure()
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          channel-id: 'C0351QXJ5CP'
          slack-message: "⛔️ Helm Charts could not be released 😱! Please check out <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Github Action workflow log>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
