name: Release Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - '!replicated/**'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

env:
  PAGES_BRANCH: ci/helm-index
  INDEX_PATH: charts/index.yaml

jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "rasabot"
          git config user.email "rasabot@rasa.com"

      # 0) Ensure ci/helm-index exists so chart-releaser has somewhere to push
      - name: Ensure ci/helm-index branch exists
        run: |
          set -euo pipefail
          if git ls-remote --exit-code --heads origin "${PAGES_BRANCH}" >/dev/null 2>&1; then
            echo "${PAGES_BRANCH} already exists."
          else
            echo "Creating ${PAGES_BRANCH}…"
            git checkout --orphan "${PAGES_BRANCH}"
            git reset --hard
            echo "# Helm index branch" > README.md
            git add README.md
            git commit -m "chore: init ${PAGES_BRANCH}"
            git remote set-url origin https://${{ secrets.CHART_RELEASER_PAT }}@github.com/${{ github.repository }}.git
            git push origin "${PAGES_BRANCH}"
            git checkout -f main
          fi

      - name: Set up Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          version: v3.15.2

      # 1) Package charts, upload to Releases, and write index.yaml to a temp branch
      - name: Run chart-releaser (packages + index → temp branch)
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
        env:
          # Use your PAT for all GitHub API calls
          CR_TOKEN: ${{ secrets.CHART_RELEASER_PAT }}
          CR_PAGES_BRANCH: ${{ env.PAGES_BRANCH }}
          CR_PAGES_INDEX_PATH: ${{ env.INDEX_PATH }}
          CR_GENERATE_RELEASE_NOTES: "true"
          CR_SKIP_EXISTING: "true"

      # 2) Pull the generated index.yaml from the temp branch (skip if branch doesn't exist yet)
      - name: Fetch updated index.yaml
        id: fetch_index
        run: |
          set -euo pipefail
          if git ls-remote --exit-code --heads origin "${PAGES_BRANCH}" >/dev/null 2>&1; then
            git fetch origin "${PAGES_BRANCH}:${PAGES_BRANCH}"
            git checkout "${PAGES_BRANCH}" -- "${INDEX_PATH}"
          else
            echo "no_index=true" >> $GITHUB_OUTPUT
          fi

      # 3) Create a PR to main with only charts/index.yaml (uses your PAT), auto-delete branch on merge
      - name: Create PR for index.yaml
        if: steps.fetch_index.outputs.no_index != 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.CHART_RELEASER_PAT }}
          commit-message: "chore(helm): update ${INDEX_PATH}"
          title: "chore(helm): update Helm index"
          branch: ci/update-helm-index
          base: main
          delete-branch: true
          labels: |
            automated
            helm
          body: |
            ## 📦 Helm Repository Index Update

            This PR updates the Helm repository index with newly released charts.
            Packages are stored as GitHub Release assets. Once merged, Pages will serve the updated index.

          add-paths: |
            charts/index.yaml

      # 2) Fetch the generated index.yaml from ci/helm-index
      - name: Fetch updated index.yaml
        run: |
          git fetch origin ci/helm-index:ci/helm-index
          git checkout ci/helm-index -- charts/index.yaml

      # 3) Open a PR with index.yaml into main, auto-delete branch when merged
      - name: Create PR for index.yaml
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(helm): update charts/index.yaml"
          title: "chore(helm): update Helm index"
          branch: ci/update-helm-index
          base: main
          delete-branch: true
          body: |
            ## 📦 Helm Repository Index Update

            This PR updates the Helm repository index with newly released charts.
            Charts are available as GitHub Release assets.

            Once merged, https://helm.rasa.com/charts will serve the updated index.
          add-paths: |
            charts/index.yaml
          labels: |
            automated
