name: Release Helm Charts to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - charts/**
      - '!replicated/**'
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  release-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      # 1) Package charts, upload as GitHub Release assets,
      #    and commit index.yaml into a temp branch (ci/helm-index)
      - name: Run chart-releaser (packages + index to temp branch)
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_PAGES_BRANCH: ci/helm-index
          CR_PAGES_INDEX_PATH: charts/index.yaml
          CR_GENERATE_RELEASE_NOTES: "true"
          CR_SKIP_EXISTING: "true"

      # 2) Fetch the temp branch with index.yaml
      - name: Fetch updated index.yaml from ci/helm-index
        run: |
          git fetch origin ci/helm-index:ci/helm-index
          git checkout ci/helm-index -- charts/index.yaml

      # 3) Open a PR with just charts/index.yaml into main
      - name: Create PR for index.yaml
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(helm): update charts/index.yaml"
          title: "chore(helm): update Helm index"
          branch: ci/update-helm-index
          base: main
          body: |
            ## 📦 Helm Repository Index Update

            This PR updates the Helm repository index with newly released charts.
            Charts are available as GitHub Release assets.

            Once merged, https://<your-domain>/charts will serve the updated index.
          add-paths: |
            charts/index.yaml
