name: Lint

on:
  pull_request:
    types: [opened, synchronize, labeled, edited]

jobs:
  lint:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'automated') }}
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Fetch history
      run: git fetch --prune

    - name: Install Helm 3
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      with:
        version: v3.11.2

    - name: Install Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.11.2' 
  
    - name: Setup Helm chart testing
      uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

    - name: Run chart-testing (list-changed)
      id: list-changed
      run: |
        changed=$(ct list-changed --config ct.yaml)
        if [[ -n "$changed" ]]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Run chart-testing (lint)
      if: steps.list-changed.outputs.changed == 'true'
      run: ct lint --config ct.yaml

    # - name: Create kind cluster
    #   if: steps.list-changed.outputs.changed == 'true'
    #   uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0

    # - name: Run chart-testing (install)
    #   run: ct install --config ct.yaml

  snyk:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'automated') }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        charts: ["studio", "rasa", "op-kits"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Fetch history
        run: git fetch --prune

      - name: Install Helm 3
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.11.2

      - name: Update dependencies
        run: helm dependency build ./charts/${{ matrix.charts }}

      - name: Generate Helm template
        run: helm template ./charts/${{ matrix.charts }} --output-dir ./output

      - name: Scan chart with Snyk IAC
        uses: snyk/actions/iac@9adf32b1121593767fc3c057af55b55db032dc04 # master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          file: ./output/
          args: --report --severity-threshold=high

      
