apiVersion: v1
kind: Service
metadata:
  name: postgres-test
  namespace: test-namespace
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-test
  namespace: test-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-test
  template:
    metadata:
      labels:
        app: postgres-test
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "test"
        - name: POSTGRES_USER
          value: "test"
        - name: POSTGRES_PASSWORD
          value: "test"

        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi 
