
name: Rasa Pro Replicated Candidate Release
run-name: Promote Replicated release to rasa-pro-release-candidate channel

on:
  push:
    branches:
      - release/*
    paths:
      - charts/rasa/**
      - replicated/**

jobs:
  check-chart-versions:
    runs-on: ubuntu-22.04 
    outputs:
      studio-version: ${{ steps.studio-chart-info.outputs.version }}
      pro-version: ${{ steps.pro-chart-info.outputs.version }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Read Rasa Studio chart
      id: pro-chart-info
      uses: miraai/read-helm-chart-yaml@9a798908719da8d062b86097d4ff1ad85abfc7aa
      with:
        path: charts/rasa/
    - name: Check Rasa Pro chart version
      env:
        VERSION: ${{ steps.pro-chart-info.outputs.name }}-${{ steps.pro-chart-info.outputs.version }}
      run: |
        if [[ $VERSION == *-rc* ]]; then
          echo "The Helm chart version is valid for a release candidate."
        else
          echo "The Helm chart version is not valid for a release candidate. Please add `-rc*` after the version in Chart.yaml."
          exit 1
        fi
    - name: Read Rasa Studio chart
      id: studio-chart-info
      uses: miraai/read-helm-chart-yaml@9a798908719da8d062b86097d4ff1ad85abfc7aa
      with:
        path: charts/studio/
  register-helm-chart:
    name: Register Rasa Pro chart
    needs: [check-chart-versions]
    uses: RasaHQ/infrasec-workflows/.github/workflows/register-private-helm-chart.yml@main
    with:
        github-repo: ${{ github.repository }}
        github-ref: ${{ github.ref }}
        chart-path: charts/rasa
        gcp-project-id: rasa-releases
        gcp-identity-provider: projects/611793044667/locations/global/workloadIdentityPools/github-actions-pool/providers/oidc-provider
        gcp-service-account: register-artifacts@rasa-releases.iam.gserviceaccount.com
        gar-location: europe-west3
        gar-repository: helm-charts  
  promote-replicated-release:
    name: Promote Replicated release
    needs: [register-helm-chart, check-chart-versions]
    uses: RasaHQ/infrasec-workflows/.github/workflows/promote-replicated-release.yml@feat/add-replicated-release-workflow
    with:
      replicated-channel: rasa-pro-release-candidate
      replicated-version: ${{ needs.check-chart-versions.outputs.pro-version }}
      pro-version: ${{ needs.check-chart-versions.outputs.pro-version }}
      studio-version: ${{ needs.check-chart-versions.outputs.studio-version }}
    secrets: inherit
