name: Rasa Pro Replicated Candidate Release
run-name: Promote Replicated release to rasa-pro-release-candidate channel

on:
  push:
    branches:
      - release/*
    paths:
      - charts/rasa/**
      - '!charts/studio/**'
      - replicated/**

jobs:
  check-chart-versions:
    name: Check chart versions
    runs-on: ubuntu-22.04
    outputs:
      studio-version: ${{ steps.studio-chart-info.outputs.version }}
      pro-version: ${{ steps.pro-chart-info.outputs.version }}
      release-candidate: ${{ steps.check-rc.outputs.rc }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - name: Read Rasa Studio chart
      id: pro-chart-info
      uses: miraai/read-helm-chart-yaml@9a798908719da8d062b86097d4ff1ad85abfc7aa
      with:
        path: charts/rasa/
    - name: Check Rasa Pro chart version
      id: check-rc
      if: github.event_name != 'pull_request' && !startsWith(github.base_ref, 'release/')
      env:
        VERSION: ${{ steps.pro-chart-info.outputs.name }}-${{ steps.pro-chart-info.outputs.version }}
      run: |
        if [[ $VERSION == *-rc* ]]; then
          echo "The Helm chart version is a release candidate."
          echo "rc=true" >> $GITHUB_OUTPUT
        else
          echo "The Helm chart version is not a release candidate. Please add `-rc*` after the version in Chart.yaml."
          echo "rc=false" >> $GITHUB_OUTPUT
        fi
    - name: Read Rasa Studio chart
      id: studio-chart-info
      uses: miraai/read-helm-chart-yaml@9a798908719da8d062b86097d4ff1ad85abfc7aa
      with:
        path: charts/studio/
  register-helm-chart:
    name: Register Rasa Pro chart
    needs: [check-chart-versions]
    if: needs.check-chart-versions.outputs.release-candidate == 'true'
    uses: RasaHQ/infrasec-workflows/.github/workflows/register-private-helm-chart.yml@main
    with:
        github-repo: ${{ github.repository }}
        github-ref: ${{ github.ref }}
        chart-path: charts/rasa
        gcp-project-id: rasa-releases
        gcp-identity-provider: projects/611793044667/locations/global/workloadIdentityPools/github-actions-pool/providers/oidc-provider
        gcp-service-account: register-artifacts@rasa-releases.iam.gserviceaccount.com
        gar-location: europe-west3
        gar-repository: helm-charts  
  promote-replicated-release:
    name: Promote Replicated release
    needs: [register-helm-chart, check-chart-versions]
    if: needs.check-chart-versions.outputs.release-candidate == 'true'
    uses: RasaHQ/infrasec-workflows/.github/workflows/promote-replicated-release.yml@main
    with:
      replicated-channel: rasa-pro-release-candidate
      replicated-version: ${{ needs.check-chart-versions.outputs.pro-version }}
      pro-version: ${{ needs.check-chart-versions.outputs.pro-version }}
      studio-version: ${{ needs.check-chart-versions.outputs.studio-version }}
    secrets: inherit
