name: Rasa Platform Replicated Stable Release
run-name: Promote Replicated release to Stable channel

on:
  workflow_dispatch:
    inputs:
      replicated-channel:
        description: The name of the Replicated channel to promote the release to
        default: Stable
        required: true
        type: string
      replicated-version:
        description: The version to assign the Replicated release
        required: true
        type: string
      studio-version:
        description: The version of the Rasa Studio chart to pull from the private registry
        required: true
        type: string

jobs:
  promote-replicated-release:
    name: Promote Replicated release
    uses: RasaHQ/infrasec-workflows/.github/workflows/promote-replicated-release.yml@main
    with:
      replicated-channel: ${{ inputs.replicated-channel }}
      replicated-version: ${{ inputs.replicated-version }}
      studio-version: ${{ inputs.studio-version }}
    secrets: inherit
