name: Release Studio Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/studio/**'
      - '!charts/rasa/**'
      - '!charts/op-kits/**'

jobs:
  release:
    name: Release Rasa Studio Helm Chart
    runs-on: ubuntu-24.04
    outputs:
      studio-version: ${{ steps.chart-info.outputs.version }}
    
    permissions:
      contents: write
      id-token: write
      pull-requests: read
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Read Helm Chart
        id: chart-info
        uses: miraai/read-helm-chart-yaml@9a798908719da8d062b86097d4ff1ad85abfc7aa # v0.1
        with:
          path: charts/studio/

      - name: Release Helm chart
        id: release
        uses: ./.github/actions/release-helm-charts-oci
        with:
          gcp-identity-provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_OIDC_HELM }}
          gcp-service-account: '${{ secrets.SERVICE_ACCOUNT_OIDC_HELM }}'
          github-repo: '${{ github.repository }}'
          github-ref: '${{ github.ref }}'
          chart-path: 'charts/studio'

      - name: Notify Slack of successful release 💬
        if: steps.release.outcome == 'success'
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C024Z61K9QU"
            text: "🚀 New *Studio* Helm Chart version `${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}` has been released!"

      - name: Notify Slack of unsuccessful release ⛔️
        if: steps.release.outcome == 'failure'
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C024Z61K9QU"
            text: "⛔️ *Studio* Helm Chart version `${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}` could not be released 😱! Please check out <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Github Action workflow log>"
