name: Rasa Studio Release Candidate
run-name: Create Studio Release Candidate

on:
  push:
    branches:
      - release/*
    paths:
      - charts/studio/**
      - '!charts/rasa/**'
      - '!charts/op-kits/**'

jobs:
  release-candidate:
    name: Studio Release Candidate
    runs-on: ubuntu-24.04
    outputs:
      studio-version: ${{ steps.check-rc.outputs.chart-version }}
      release-candidate: ${{ steps.check-rc.outputs.is-rc }}
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check Rasa Studio chart version
        id: check-rc
        uses: ./.github/actions/check-chart-rc
        with:
          chart-path: charts/studio

      - name: Release Helm chart
        id: release
        if: steps.check-rc.outputs.is-rc == 'true'
        uses: ./.github/actions/release-helm-charts-oci
        with:
          gcp-identity-provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_OIDC_HELM }}
          gcp-service-account: '${{ secrets.SERVICE_ACCOUNT_OIDC_HELM }}'
          github-repo: '${{ github.repository }}'
          github-ref: '${{ github.ref }}'
          chart-path: 'charts/studio'
