name: Release Rasa Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/rasa/**'
      - '!charts/studio/**'
      - '!charts/op-kits/**'
      - '!replicated/**'

env:
  ARTIFACT_REGISTRY: europe-west3-docker.pkg.dev
  HELM_REPOSITORY: rasa-releases
  HELM_CHART: helm-charts

jobs:
  release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write
      pull-requests: read
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: Install Helm 3
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78
        with:
          version: v3.15.2

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_OIDC_HELM }}
          service_account: '${{ secrets.SERVICE_ACCOUNT_OIDC_HELM }}'

      - name: Login to Helm registry using Google Auth token
        run: |-
          echo '${{ steps.auth.outputs.access_token }}' | helm registry login -u oauth2accesstoken --password-stdin https://${{ env.ARTIFACT_REGISTRY }}

      - name: Read Helm Chart
        id: chart-info
        uses: miraai/read-helm-chart-yaml@9a798908719da8d062b86097d4ff1ad85abfc7aa
        with:
          path: charts/rasa/

      - name: Package Helm release
        id: package
        run: helm package charts/rasa/ --dependency-update

      - name: Push Helm Charts to Google Artifact Registry
        id: release
        run: helm push ${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}.tgz oci://${{ env.ARTIFACT_REGISTRY }}/${{ env.HELM_REPOSITORY }}/${{ env.HELM_CHART }}

      - name: Notify Slack of successful release 💬
        if: steps.release.outcome == 'success'
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          # Send notication to #release slack channel
          channel-id: 'C024Z61K9QU'
          slack-message: "🚀 New *Rasa* Helm Chart version `${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}` has been released!"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack of unsuccessful release ⛔️
        if: steps.release.outcome == 'failure'
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          # Send notication to #release slack channel
          channel-id: 'C024Z61K9QU'
          slack-message: "⛔️ *Rasa* Helm Chart version `${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}` could not be released 😱! Please check out <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|Github Action workflow log>"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
