# Trigger the workflow on milestone events.
name: Create Release Notes

on: 
  push:
    branches: 
      - release-notes
    paths:
      - 'charts/rasa/**'
      - '!charts/studio/**'

jobs:
  create-release-notes:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          fetch-depth: 0
    
      - name: Read Helm Chart
        id: chart-info
        uses: miraai/read-helm-chart-yaml@9a798908719da8d062b86097d4ff1ad85abfc7aa
        with:
          path: charts/rasa/
        
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}"

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## 📦 Rasa",
                    "labels": ["rasa"]
                },
                {
                    "title": "## 📦 Studio",
                    "labels": ["studio"]
                }
              ]
            }
          fromTag: "rasa-0.1.23"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          tag_name: ${{ steps.chart-info.outputs.name }}-${{ steps.chart-info.outputs.version }}
          body: ${{steps.github_release.outputs.changelog}}
