name: Release Op-Kits Helm Chart

on:
  push:
    branches:
      - test-slack-notifications/

jobs:
  release:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      id-token: write
      pull-requests: read
      issues: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Notify Slack of successful release 💬
        uses: slackapi/slack-github-action@007b2c3c751a190b6f0f040e47ed024deaa72844
        with:
          # Send notication to #release slack channel
          channel-id: 'C0351QXJ5CP'
          slack-message: "🚀 New *Op-Kits* Helm Chart version `op-kits-0.1.2` has been released!"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
