apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-redis-service
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
